### ISSUE TITLE
Fabryka zamiast konstruktora w klasie Word

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [levant9/tasks#12]
Używasz dwu konstruktorów w tej klasie, każdy woła metodę `setActual` która naprawdę nie powinna się tak nazywać.

1. zamiast konstruktorów - statyczne metody fabryczne
2. ew. budowniczy
3. setActual powinno zmienić nazwę, bo nie jest metodą ustawiającą - ma logikę
4. setter nie powinien być wołany z konstruktora. 
5. API Stringa: `repeat`. JDK10 OIDP.

**Comment by levant9** [comment]
zrefaktorowane
