### ISSUE TITLE
Wyjątek bynajmniej nie-wyjątkowy

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [levant9/tasks#13]
Wyjątki powinny wskazywać wyjątkową sytuację w grze.

`GameOverException` - nomen omen - nie jest wyjątkowy.

Do tego rzucasz go z metody sprawdzającej koniec gry, która mimo nazwy `check` zwraca `void`. Niech metoda zwraca `boolean`, tym bardziej, że w środku ma tylko `if`a. Jakby zwracała wartość tego `if`a to miałbyś z głowy wyjątek bo metoda powiedziałaby Ci czy koniec gry czy nie. 

Jeśli koniec programu może nastąpić naturalnie a nie przez wyjątek czy inne takie - niech nastąpi naturalnie (czyli przez dojście do ostatniej instrukcji).

**Comment by levant9** [comment]
prawda, usuniety :)
