### ISSUE TITLE
Losowanie słowa

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [levant9/tasks#15]
Niezły pomysł z enumem - klasa nawet ładna.

Natomiast jak już masz enuma... czemu nie rozlosować wartości z niego? Enumy mogą mieć metody. 

Niech zatem enum stanie się obiektem pierwszej kategorii i niech ma metodę zwracającą Stringa, losującą wartość.

**Comment by levant9** [comment]
zrobione
