### ISSUE TITLE
Szubienica i jej szablon

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [levant9/tasks#16]
Uczciwie rzecz biorąc nieźle zrobione, natomiast można je jeszcze trochę ulepszyć.

Na ten przykład, nie potrzebujesz metody zwracającej szablon (getGibbetTemplate). To wybebeszanie stanu i chcesz go unikać (enkapsulacja, pamiętasz?). Jeśli potrzebujesz wiedzieć czy to już ostatnie odgadywanie, możesz zapytać szablon (delegacja z szubienicy do szablonu) a szablon może odpowiedzieć czy tak czy nie.

Wreszcie: niezbyt dobry nawyk, że puste konstruktory rozwlekasz na dwie linie:

```
Konstruktor() {
}
```

**Comment by levant9** [comment]
fixed

**Comment by levant9** [comment]
Co do konstruktorow, to tak mi samo IDE robi :P
