### ISSUE TITLE
FileCreator error handling

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [levant9/tasks#4]
https://github.com/levant9/tasks/blob/f34bec2e2093dd91aaa4bb5fb6639ad23553e0fc/random-words-to-file/src/main/java/pl/lvt/random_words_to_file/FileCreator.java#L18

Why IllegalState instead of - say - dedicated IOE variant?

**Comment by levant9** [comment]
Which would be better, any suggestion?

**Comment by LIttleAncientForestKami** [comment]
Some IOException variant? That's hardly a state problem.
